Controllers/EcoScoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using COMP2084___A1.Models;
using Microsoft.AspNetCore.Authorization;

namespace COMP2084___A1.Controllers
{
    [Authorize(Roles = "Administrator, Customer")]
    public class EcoScoresController : Controller
    {
        private readonly COMP2084_A1_V3Context _context;

        public EcoScoresController(COMP2084_A1_V3Context context)
        {
            _context = context;
        }
        [AllowAnonymous]
        // GET: EcoScores
        public async Task<IActionResult> Index()
        {
            return View(await _context.EcoScore.ToListAsync());
        }

        // GET: EcoScores/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ecoScore = await _context.EcoScore
                .FirstOrDefaultAsync(m => m.EcoscoreId == id);
            if (ecoScore == null)
            {
                return NotFound();
            }

            return View(ecoScore);
        }
        [Authorize]
        // GET: EcoScores/Create

        public IActionResult Create()
        {
            return View();
        }

        // POST: EcoScores/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EcoscoreId,ObjectName,Description,Reuse,Reduce,Recycle,Photo,Ecoscore1")] EcoScore ecoScore)
        {
            if (ModelState.IsValid)
            {
                _context.Add(ecoScore);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(ecoScore);
        }

        // GET: EcoScores/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ecoScore = await _context.EcoScore.FindAsync(id);
            if (ecoScore == null)
            {
                return NotFound();
            }
            return View(ecoScore);
        }

        // POST: EcoScores/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EcoscoreId,ObjectName,Description,Reuse,Reduce,Recycle,Photo,Ecoscore1")] EcoScore ecoScore)
        {
            if (id != ecoScore.EcoscoreId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ecoScore);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EcoScoreExists(ecoScore.EcoscoreId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(ecoScore);
        }

        // GET: EcoScores/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ecoScore = await _context.EcoScore
                .FirstOrDefaultAsync(m => m.EcoscoreId == id);
            if (ecoScore == null)
            {
                return NotFound();
            }

            return View(ecoScore);
        }

        // POST: EcoScores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ecoScore = await _context.EcoScore.FindAsync(id);
            _context.EcoScore.Remove(ecoScore);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EcoScoreExists(int id)
        {
            return _context.EcoScore.Any(e => e.EcoscoreId == id);
        }
    }
}

Controllers/UserSelectionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using COMP2084___A1.Models;
using Microsoft.AspNetCore.Authorization;

namespace COMP2084___A1.Controllers
{
    [Authorize (Roles = "Administrator, Customer")]
    public class UserSelectionsController : Controller
    {
        private readonly COMP2084_A1_V3Context _context;

        public UserSelectionsController(COMP2084_A1_V3Context context)
        {
            _context = context;
        }
        
        // GET: UserSelections
        public async Task<IActionResult> Index()
        {
            var cOMP2084_A1_V3Context = _context.UserSelection.Include(u => u.EcoscoreNavigation);
            
            return View(await cOMP2084_A1_V3Context.ToListAsync());
        }

        // GET: UserSelections/Details/5
        public async Task<IActionResult> Details(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var userSelection = await _context.UserSelection
                .Include(u => u.EcoscoreNavigation)
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (userSelection == null)
            {
                return NotFound();
            }

            return View(userSelection);
        }

        // GET: UserSelections/Create
        [Authorize]
        public IActionResult Create()
        {
            ViewData["EcoscoreId"] = new SelectList(_context.EcoScore.OrderBy(c => c.EcoscoreId), "EcoscoreId", "EcoscoreId");
            ViewData["objectName"] = new SelectList(_context.EcoScore, "objectName", "objectName"); ////
            return View();
        }

        // POST: UserSelections/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserId,FullName,ObjectName,Description,Reuse,Reduce,Recycle,Photo,Ecoscore,EcoscoreId")] UserSelection userSelection)
        {
            if (ModelState.IsValid)
            {
                _context.Add(userSelection);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["EcoscoreId"] = new SelectList(_context.EcoScore.OrderBy(c => c.EcoscoreId), "EcoscoreId", "EcoscoreId", userSelection.EcoscoreId);
            ViewData["objectName"] = new SelectList(_context.EcoScore, "objectName", "objectName", userSelection.ObjectName);
            return View(userSelection);
        }

        // GET: UserSelections/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userSelection = await _context.UserSelection.FindAsync(id);
            if (userSelection == null)
            {
                return NotFound();
            }
            ViewData["EcoscoreId"] = new SelectList(_context.EcoScore.OrderBy(c => c.EcoscoreId), "EcoscoreId", "EcoscoreId", userSelection.EcoscoreId);
            ViewData["objectName"] = new SelectList(_context.EcoScore, "objectName", "objectName", userSelection.ObjectName);
            return View(userSelection);
        }

        // POST: UserSelections/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserId,FullName,ObjectName,Description,Reuse,Reduce,Recycle,Photo,Ecoscore,EcoscoreId")] UserSelection userSelection)
        {
            if (id != userSelection.UserId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(userSelection);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserSelectionExists(userSelection.UserId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EcoscoreId"] = new SelectList(_context.EcoScore.OrderBy(c => c.EcoscoreId), "EcoscoreId", "EcoscoreId", userSelection.EcoscoreId);
            ViewData["objectName"] = new SelectList(_context.EcoScore, "objectName", "objectName", userSelection.ObjectName);
            return View(userSelection);
        }

        // GET: UserSelections/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userSelection = await _context.UserSelection
                .Include(u => u.EcoscoreNavigation)
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (userSelection == null)
            {
                return NotFound();
            }

            return View(userSelection);
        }

        // POST: UserSelections/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var userSelection = await _context.UserSelection.FindAsync(id);
            _context.UserSelection.Remove(userSelection);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserSelectionExists(int id)
        {
            return _context.UserSelection.Any(e => e.UserId == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RePsychle</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/img/white_logo.png" /></a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (!User.IsInRole("Administrator"))
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EcoScores" asp-action="Index">EcoScores</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UserSelections" asp-action="Index">User Selection</a>
                        </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; Wyatt Kirschner - 200407722 - COMP2084 - A1
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/sorttable.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>